<?php 

//櫻間
$hos_div=$_SESSION['update']['hos_div'];
$op_flg=$_SESSION['update']['op_flg'];
$clo_day=$_SESSION['update']['clo_day'];
$med_ass=$_SESSION['update']['med_ass'];
$hos_name=$_SESSION['update']['hos_name'];
$zipcode=$_SESSION['update']['zipcode'];
$are_cd=$_SESSION['update']['are_cd'];
$area=$_SESSION['update']['area'];
$pre=$_SESSION['update']['pre'];
$city=$_SESSION['update']['city'];
$zone=$_SESSION['update']['zone'];
$town=$_SESSION['update']['town'];
$str_num=$_SESSION['update']['str_num'];
$tel=$_SESSION['update']['tel'];
$fax=$_SESSION['update']['fax'];
//櫻間20230317
$mail=$_SESSION['update']['mail'];
$note=$_SESSION['update']['note'];